name: Update Python Data

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  "0 0 * * *"
  push:
    
# on:
#   [push]


jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      # Install python
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install python dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
        
      # Build the site
      - name: Build the site
        run: |
          sh build.sh


      - name: Commit files - Removes
        run:
          git config --local user.name actions-user

          git config --local user.email "actions@github.com" 
          
          git fetch

          git add *

          git commit -am "GH Action File removed $(date)" 
 
          git push -f origin main
